INSERT INTO department (id, dept_name)
VALUES (1,"Sales Team")
       (002,"Customer Support")
       (003,"Maintenence")
       (004,"")
INSERT INTO role (id, title, salary, department_id)
VALUES (1,"")
       (2,"")
       (3,"")
       (4,"")

INSERT INTO employee (id, first_name, last_name, role_id, manager_id)
VALUES (1,"")
       (2,"")
       (3,"")
       (4,"")
       (5,"")
       (6,"")
       (7,"")
       (8,"")